AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Resources:
  Courselist:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Courselist"
      AttributeDefinitions:
        - AttributeName: department
          AttributeType: S
        - AttributeName: course_code
          AttributeType: S
      KeySchema:
        - AttributeName: department
          KeyType: HASH
        - AttributeName: course_code
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  engCourses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "engCourses"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: Department
          AttributeType: S
        - AttributeName: CourseCode
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsiCategoryCourses
          KeySchema:
            - AttributeName: Department
              KeyType: HASH
            - AttributeName: CourseCode
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  engPrograms:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "engPrograms"
      AttributeDefinitions:
        - AttributeName: Department
          AttributeType: S
        - AttributeName: Program
          AttributeType: S
      KeySchema:
        - AttributeName: Department
          KeyType: HASH
        - AttributeName: Program
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
Outputs:
  CourseDynamoDBTable:
    Value: !Ref "engCourses"
    Export:
      Name: CourseDynamoDBTable
  ProgramDynamoDBTable:
    Value: !Ref "engPrograms"
    Export:
      Name: ProgramDynamoDBTable
  CourselistDynamoDBTable:
    Value: !Ref "Courselist"
    Export:
      Name: CourselistDynamoDBTable
